#!/usr/bin/env bash
#Write a Bash script that:
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and
#terminates itself when receiving a SIGQUIT or SIGTERM signal

i="1"
sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
kil_hate()
{
	echo "I hate the kill command"
	sudo rm /var/run/myscript.pid
}
y_d_love()
{
	echo "Y U no love me?!"
}
trap 'kil_hate; exit' SIGTERM
trap 'y_d_love; exit' SIGINT
trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
while [ $i -eq 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done
