#!/usr/bin/env bash
#Bash script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#Iam invincible!!! when receiving a SIGTERM signal

i="1"
while [ $i -eq 1 ]
do
	echo "To infinity and beyond"
	sleep 2
done
trap 'echo "I am invincible!!!"' SIGTERM
