#!/usr/bin/env bash
#displays numbers from 1 to 100
#FizzBuzz when the number is a multiple of 3 and 5
#Fizz when the number is multiple of 3
#Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format

for n in {1..100}
do
if ((n % 15 == 0))
then
	echo "FizzBuzz"
elif ((n % 5 == 0))
then
	echo "Buzz"
elif (( n % 3 == 0))
then
	echo "Fizz"
else
	echo "$i"
fi
done
