#!/usr/bin/env bash
#plays the content of the file /etc/passwd
#Your script should only display:
#username
#user id
#Home directory path for the user

while read -r passwd;
do
	echo "$passwd" | cut -d ":" -f1,2,6
done < "/etc/passwd"
