#!/usr/bin/env bash
#4 bad luck, 8 is your chance
COUNT=0
while [ $COUNT -lt 10 ]
do
	if [ $COUNT -eq 3 ]
	then
		echo "bad luck"
	elif [ $COUNT -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	let COUNT+=1
done
