#!/usr/bin/env bash
#4 bad luck, 8 is your chance

COUNT=1
while [ $COUNT -lt 11 ]
do
	if [ $COUNT = 4 ]
	then
		echo "bad luck"
	elif [ $COUNT = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	let COUNT+=1
done
