#!/usr/bin/env bash
# Bash script that displays from 1 to 20 and:
# if 4 display bad luck from China
# if 9 and then bad luck from Japan
# if 17 and then bad luck from Italy
i="1"
while [ $i -le 20 ]
do
case $i in
	4) 
		echo $i
		echo "bad luck from China"
		;;
	9)
		echo $i
		echo "bad luck from Japan"
		;;
	17)
		echo $i 
		echo "bad luck from Italy"
		;;
	*)
		echo $i
esac
i=$((i+1))
done
